version: 2.1

jobs:
  build:            
    docker:         
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14  
      - run:
          name: Build docker container for earch microservices
          command: |

            echo "------------Build docker images----------"

            docker build -t udagram-api-user ./udagram-api-user        
            docker tag udagram-api-user longcv2/udagram-api-user:v1

            docker build -t udagram-api-feed ./udagram-api-feed        
            docker tag udagram-api-feed longcv2/udagram-api-feed:v1
                   
            docker build -t udagram-frontend ./udagram-frontend        
            docker tag udagram-frontend longcv2/udagram-frontend:v1

            docker build -t udagram-reverseproxy ./udagram-reverseproxy        
            docker tag udagram-reverseproxy longcv2/udagram-reverseproxy:v1           

            echo "-------------Build done ------------"        

            echo "-------------Login dockerhub------------" 
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            
            echo "-------------Push images to dockerhub------------" 
            docker push longcv2/udagram-reverseproxy:v1        
            docker push longcv2/udagram-api-user:v1
            docker push longcv2/udagram-api-feed:v1
            docker push longcv2/udagram-frontend:v1
workflows:
  default:
    jobs:
      - build